name: app
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - pip
  - pillow
  - watchdog
  - requests
  - pip:
      - pyinstaller>=6.6,<7
      - pystray>=0.19,<1
      - sv-ttk>=2.6,<3
